scrapping_lands:
  cron: "1 17 * * *"
  class: "DistributeJob"
  queue: default
scrapping_addresses:
  cron: "1 16 * * *"
  class: "ScrappingAddressesJob"
  queue: default
post_bargain:
  cron: "3 16 * * *"
  class: "PostBargainJob"
  queue: default

correct_data:
  cron: "3 16 * * *"
  class: "CorrectDataJob"
  queue: default

logging_prices:
  cron: "3 16 * * *"
  class: "LoggingPriceJob"
  queue: default