scrapping_lands:
  cron: "1 17 * * *"
  class: "DistributeJob"
  queue: default
scrapping_addresses:
  cron: "1 16 * * *"
  class: "ScrappingAddressesJob"
  queue: default
post_bargain:
  cron: "3 12 * * *"
  class: "PostBargainJob"
  queue: default

correct_data:
  cron: "3 16 * * *"
  class: "CorrectDataJob"
  queue: default

logging_prices:
  cron: "0 0 * * SUN"
  class: "LoggingPriceJob"
  queue: default

generate_sitemap:
  cron: "0 1 * * *"
  class: "SitemapGeneratorJob"
  queue: default

logging_address_attributes:
  cron: "0 */6 * * *"
  class: "AddressPriceLoggerJob"
  queue: default