scrapping_addresses:
  cron: "1 16 * * *"
  class: "ScrappingAddressesJob"
  queue: default

first_scope_districts:
  cron: "2 16 * * *"
  class: "ScrappingLandsJob"
  queue: critical
  args: [ 'asc' ]

second_scope_districts:
  cron: "3 16 * * *"
  class: "ScrappingLandsJob"
  queue: critical

post_bargain:
  cron: "3 16 * * *"
  class: "PostBargainJob"
  queue: default
