first_scope_districts:
  cron: "1 15 * * *"
  class: "ScrappingLandsJob"
  queue: critical
  args: [ 0 ]

second_scope_districts:
  cron: "2 15 * * *"
  class: "ScrappingLandsJob"
  queue: critical
  args: [ 3 ]

third_scope_districts:
  cron: "3 15 * * *"
  class: "ScrappingLandsJob"
  queue: critical
  args: [ 6 ]

fourth_scope_districts:
  cron: "4 15 * * *"
  class: "ScrappingLandsJob"
  queue: critical
  args: [ 9 ]

fifth_scope_districts:
  cron: "5 15 * * *"
  class: "ScrappingLandsJob"
  queue: critical
  args: [ 12 ]

sixth_scope_districts:
  cron: "6 15 * * *"
  class: "ScrappingLandsJob"
  queue: critical
  args: [ 15 ]

seventh_scope_districts:
  cron: "7 15 * * *"
  class: "ScrappingLandsJob"
  queue: critical
  args: [ 18 ]

eighth_scope_districts:
  cron: "8 15 * * *"
  class: "ScrappingLandsJob"
  queue: critical
  args: [ 21 ]
